spring:
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  modulith:
    events:
      jdbc-enabled: true
  servlet:
    multipart:
      enabled: true


app:
  security:
    jwt:
      secretKey: ${JWT_SECRET_KEY}
      expirationTime: 3600
      algorithm: HS256
  cloudinary:
    url: ${CLOUDINARY_URL}

  open-api:
    server:
      url: http://localhost:8081
      description: API for restaurant management solutions
    info:
      title: Restaurant management solutions
      version: 1.0.0
      description: |
        still need to provide desription for this
      contact:
        name: Aymane El Maini
        email: elmainiaymane03@gmail.com
        url: https://aymaneelmaini.vercel.app

logging:
  level:
    org.springframework.jdbc: debug
    org.springframework.security: trace
