name: Backend Pipline

on:
  pull_request:
    branches:
      - "main"
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Package the appllication
        run: cd backend && mvn clean package -DskipTests
  
  test_and_report:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Tests
        run: cd backend && mvn clean test

      - name: Upload Test Reports
        uses: dorny/test-reporter@v1
        if: success()
        with:
          name: "Unit Test Results"
          path: "**/target/surefire-reports/*.xml"
          reporter: java-junit
